[package]
name = "rust_lib_m3u8_downloader"
version = "0.1.3"
edition = "2021"
rust-version = "1.88"
license-file = "../LICENSE"
authors = ["blueokanna"]
description = "FerrisLoad application runtime and Flutter bridge"
repository = "https://github.com/blueokanna/m3u8-downloader"

[workspace]
members = ["core"]
resolver = "2"

[lib]
name = "rust_lib_m3u8_downloader"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
aes = "0.9"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
ferrisload-core = { path = "core", version = "0.1.3", features = ["std"] }

flutter_rust_bridge = "=2.12.0"

hex = "0.4.3"
indicatif = "0.18.6"
jni = "0.22.4"
log = "0.4.34"
env_logger = "0.11.11"

regex = "1.13.1"

nextjson = { version = "0.1.4", features = ["derive", "std"] }
tzcraft = { version = "0.1.1", default-features = false, features = [
    "std",
    "serde",
] }
courierust = "1.0.1"
webpki-root-certs = "1.0.9"
url = "2.5.8"
uuid = { version = "1.25.0", features = ["v4"] }
dashmap = "6.2.1"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.15.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[[bin]]
name = "m3u8_api_server"
path = "src/bin/m3u8_api_server.rs"
