// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `android_hardware_transcode`, `check_ffmpeg`, `container_from_url`, `convert_to_mp4`, `create_http_client_for_context`, `create_http_client`, `detect_acceleration`, `detect_access_challenge`, `direct_media_candidate`, `download_and_merge`, `download_playlist`, `download_to_file`, `extract_bilibili_candidates`, `extract_generic_candidates`, `extract_json_object_after`, `extract_page_title`, `extract_youtube_candidates`, `extractor_name_for_host`, `finish`, `html_unescape`, `infer_title_from_url`, `init_runtime_logging`, `inspect_hls_metadata`, `is_hls_like`, `is_supported_media_like`, `merge_media_streams`, `mime_from_extension`, `mime_from_urls`, `new`, `normalize_exposed_media_url`, `protocol_from_url`, `push_generic_candidate`, `push`, `retry_backoff_delay`, `run_hls_pipeline`, `score_candidates`, `select_transcoder_backend`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AccelType`, `CandidateCollector`, `TranscoderKind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`

Stream<ProgressUpdate> hls2Mp4Run({
  required String url,
  required int concurrency,
  required String output,
  required int retries,
  required int videoBitrate,
  required int audioBitrate,
  required bool keepTemp,
}) => RustLib.instance.api.crateApiDownloaderHls2Mp4Run(
  url: url,
  concurrency: concurrency,
  output: output,
  retries: retries,
  videoBitrate: videoBitrate,
  audioBitrate: audioBitrate,
  keepTemp: keepTemp,
);

Future<MediaInspectionResult> inspectMediaFromUrl({required String url}) =>
    RustLib.instance.api.crateApiDownloaderInspectMediaFromUrl(url: url);

Future<MediaInspectionResult> inspectMediaWithContext({
  required String url,
  required RequestContext requestContext,
}) => RustLib.instance.api.crateApiDownloaderInspectMediaWithContext(
  url: url,
  requestContext: requestContext,
);

Stream<ProgressUpdate> downloadMediaRun({
  required String pageUrl,
  required String mediaUrl,
  String? audioUrl,
  required String output,
  required int concurrency,
  required int retries,
  required int videoBitrate,
  required int audioBitrate,
  required bool keepTemp,
}) => RustLib.instance.api.crateApiDownloaderDownloadMediaRun(
  pageUrl: pageUrl,
  mediaUrl: mediaUrl,
  audioUrl: audioUrl,
  output: output,
  concurrency: concurrency,
  retries: retries,
  videoBitrate: videoBitrate,
  audioBitrate: audioBitrate,
  keepTemp: keepTemp,
);

Stream<ProgressUpdate> downloadMediaWithContext({
  required String pageUrl,
  required String mediaUrl,
  String? audioUrl,
  required String output,
  required int concurrency,
  required int retries,
  required int videoBitrate,
  required int audioBitrate,
  required bool keepTemp,
  required RequestContext requestContext,
}) => RustLib.instance.api.crateApiDownloaderDownloadMediaWithContext(
  pageUrl: pageUrl,
  mediaUrl: mediaUrl,
  audioUrl: audioUrl,
  output: output,
  concurrency: concurrency,
  retries: retries,
  videoBitrate: videoBitrate,
  audioBitrate: audioBitrate,
  keepTemp: keepTemp,
  requestContext: requestContext,
);

class HeaderEntry {
  final String name;
  final String value;

  const HeaderEntry({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeaderEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class MediaCandidate {
  final String id;
  final String title;
  final String extractor;
  final String pageUrl;
  final String mediaUrl;
  final String? audioUrl;
  final String container;
  final String protocol;
  final String mimeType;
  final String qualityLabel;
  final int width;
  final int height;
  final bool requiresFfmpeg;
  final int score;
  final int segmentCount;
  final double durationSeconds;
  final bool primary;
  final String reason;

  const MediaCandidate({
    required this.id,
    required this.title,
    required this.extractor,
    required this.pageUrl,
    required this.mediaUrl,
    this.audioUrl,
    required this.container,
    required this.protocol,
    required this.mimeType,
    required this.qualityLabel,
    required this.width,
    required this.height,
    required this.requiresFfmpeg,
    required this.score,
    required this.segmentCount,
    required this.durationSeconds,
    required this.primary,
    required this.reason,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      extractor.hashCode ^
      pageUrl.hashCode ^
      mediaUrl.hashCode ^
      audioUrl.hashCode ^
      container.hashCode ^
      protocol.hashCode ^
      mimeType.hashCode ^
      qualityLabel.hashCode ^
      width.hashCode ^
      height.hashCode ^
      requiresFfmpeg.hashCode ^
      score.hashCode ^
      segmentCount.hashCode ^
      durationSeconds.hashCode ^
      primary.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaCandidate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          extractor == other.extractor &&
          pageUrl == other.pageUrl &&
          mediaUrl == other.mediaUrl &&
          audioUrl == other.audioUrl &&
          container == other.container &&
          protocol == other.protocol &&
          mimeType == other.mimeType &&
          qualityLabel == other.qualityLabel &&
          width == other.width &&
          height == other.height &&
          requiresFfmpeg == other.requiresFfmpeg &&
          score == other.score &&
          segmentCount == other.segmentCount &&
          durationSeconds == other.durationSeconds &&
          primary == other.primary &&
          reason == other.reason;
}

class MediaInspectionResult {
  final String pageUrl;
  final String pageTitle;
  final String extractor;
  final List<MediaCandidate> candidates;
  final List<String> warnings;
  final bool authRequired;
  final String challengeReason;

  const MediaInspectionResult({
    required this.pageUrl,
    required this.pageTitle,
    required this.extractor,
    required this.candidates,
    required this.warnings,
    required this.authRequired,
    required this.challengeReason,
  });

  @override
  int get hashCode =>
      pageUrl.hashCode ^
      pageTitle.hashCode ^
      extractor.hashCode ^
      candidates.hashCode ^
      warnings.hashCode ^
      authRequired.hashCode ^
      challengeReason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaInspectionResult &&
          runtimeType == other.runtimeType &&
          pageUrl == other.pageUrl &&
          pageTitle == other.pageTitle &&
          extractor == other.extractor &&
          candidates == other.candidates &&
          warnings == other.warnings &&
          authRequired == other.authRequired &&
          challengeReason == other.challengeReason;
}

class ProgressUpdate {
  final String message;
  final double progress;

  const ProgressUpdate({required this.message, required this.progress});

  @override
  int get hashCode => message.hashCode ^ progress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressUpdate &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          progress == other.progress;
}

class RequestContext {
  final String userAgent;
  final String referer;
  final String origin;
  final String cookie;
  final List<HeaderEntry> headers;

  const RequestContext({
    required this.userAgent,
    required this.referer,
    required this.origin,
    required this.cookie,
    required this.headers,
  });

  static Future<RequestContext> default_() =>
      RustLib.instance.api.crateApiDownloaderRequestContextDefault();

  @override
  int get hashCode =>
      userAgent.hashCode ^
      referer.hashCode ^
      origin.hashCode ^
      cookie.hashCode ^
      headers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestContext &&
          runtimeType == other.runtimeType &&
          userAgent == other.userAgent &&
          referer == other.referer &&
          origin == other.origin &&
          cookie == other.cookie &&
          headers == other.headers;
}
