import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('zh'),
    Locale.fromSubtags(languageCode: 'zh', scriptCode: 'Hant'),
    Locale('ja'),
    Locale('ko'),
    Locale('ar'),
    Locale('hi'),
    Locale('ru'),
    Locale('es'),
    Locale('fr'),
    Locale('de'),
    Locale('pt'),
    Locale('tr'),
    Locale('vi'),
    Locale('id'),
    Locale('fa'),
    Locale('ur'),
    Locale('ug'),
    Locale('ku'),
    Locale('uk'),
    Locale('ms'),
    Locale('it'),
    Locale('nl'),
    Locale('sv'),
  ];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(value != null, 'AppLocalizations not found in context');
    return value!;
  }

  static const localeLabels = <String, String>{
    'en': 'English',
    'zh': '简体中文',
    'zh_Hant': '繁體中文',
    'ja': '日本語',
    'ko': '한국어',
    'ar': 'العربية',
    'hi': 'हिन्दी',
    'ru': 'Русский',
    'es': 'Español',
    'fr': 'Français',
    'de': 'Deutsch',
    'pt': 'Português',
    'tr': 'Türkçe',
    'vi': 'Tiếng Việt',
    'id': 'Bahasa Indonesia',
    'fa': 'فارسی',
    'ur': 'اردو',
    'ug': 'ئۇيغۇرچە',
    'ku': 'Kurdî',
    'uk': 'Українська',
    'ms': 'Bahasa Melayu',
    'it': 'Italiano',
    'nl': 'Nederlands',
    'sv': 'Svenska',
  };

  static const _fallbackLocale = 'en';

  static const _strings = <String, Map<String, String>>{
    'en': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Inspect pages, locate playable media, and download the best exposed stream.',
      'input_source': 'Source URL',
      'source_hint': 'Paste a webpage, m3u8, mp4, YouTube or Bilibili link',
      'file_name': 'Output file',
      'save_location': 'Save location',
      'default_location': 'Default output location',
      'choose_directory': 'Choose directory',
      'reset_default': 'Use default',
      'analyze': 'Analyze source',
      'download': 'Download selected stream',
      'download_options': 'Download options',
      'concurrency': 'Concurrency',
      'retries': 'Retries',
      'video_bitrate': 'Video bitrate',
      'audio_bitrate': 'Audio bitrate',
      'keep_temp': 'Keep temporary files',
      'keep_temp_hint': 'Useful for diagnostics and manual remuxing',
      'analysis_results': 'Detected media',
      'status': 'Status',
      'history': 'History',
      'warnings': 'Warnings',
      'appearance': 'Appearance',
      'mode': 'Mode',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'theme': 'Theme',
      'language': 'Language',
      'battery': 'Battery optimization',
      'battery_hint':
          'Disable restrictions to keep long downloads alive in the background',
      'disable_now': 'Disable now',
      'no_candidates': 'No downloadable media candidates were detected yet.',
      'select_candidate': 'Select a media candidate before downloading.',
      'source_page': 'Source page',
      'extractor': 'Extractor',
      'completed': 'Completed',
      'output_path': 'Saved file',
      'analyzing': 'Analyzing source...',
      'ready': 'Candidate ready',
      'inspector': 'Inspector',
      'stream': 'Stream',
      'authorization': 'Authorized request context',
      'authorization_hint':
          'For owned or authorized sites: Cookie, User-Agent, Referer, Origin, and custom headers',
      'cookie_hint': 'name=value; another=value',
      'headers_hint':
          'Authorization: Bearer ...\nX-Requested-With: XMLHttpRequest',
      'core': 'CORE',
      'score': 'Score',
      'segments': 'segments',
      'auth_browser_open': 'Open auth browser',
      'auth_browser_title': 'Authorized session browser',
      'auth_browser_hint':
          'Open the target site here, complete login or human verification yourself, then import the current session back into FerrisLoad.',
      'auth_browser_hint_inline':
          'Use the auth browser when the site requires login, cookie-bound playback, or a human verification page.',
      'auth_browser_address': 'Browser address',
      'auth_browser_go': 'Go',
      'auth_browser_import': 'Import current session',
      'auth_browser_no_session':
          'No reusable cookies or browser session were found on the current page.',
      'auth_session_imported':
          'Authorized session imported. You can analyze or download again with the updated request context.',
      'auth_challenge_detected': 'Access challenge detected',
      'auth_challenge_help':
          'FerrisLoad can reuse a session you complete yourself, but it will not bypass Cloudflare, CAPTCHA, bans, DRM, signatures, or preview limits.',
      'auth_auto_open': 'Automatically open auth browser on challenge',
      'auth_auto_open_hint':
          'When inspection or downloading hits login, rate-limit, or human-verification challenges, FerrisLoad opens the authorized session browser automatically.',
      'auth_redirecting':
          'Authorization challenge detected. Opening auth browser...',
      'clear_auth_context': 'Clear imported session',
      'preparing': 'Preparing download...',
      'output_not_created':
          'The download finished but no output file was produced. Check the source URL, request context, or try again.',
      'export_failed':
          'Failed to export the file to the selected location. Temporary output:',
      'download_hint':
          'You can download directly without analyzing: paste an m3u8 or direct media link and start.',
    },
    'zh': {
      'app_title': 'FerrisLoad',
      'app_subtitle': '分析网页、定位可播放媒体，并下载当前页面暴露出的最佳核心流。',
      'input_source': '资源地址',
      'source_hint': '粘贴网页、m3u8、mp4、YouTube 或 Bilibili 链接',
      'file_name': '输出文件',
      'save_location': '保存位置',
      'default_location': '默认输出位置',
      'choose_directory': '选择目录',
      'reset_default': '恢复默认',
      'analyze': '分析资源',
      'download': '下载已选核心流',
      'download_options': '下载参数',
      'concurrency': '并发',
      'retries': '重试',
      'video_bitrate': '视频码率',
      'audio_bitrate': '音频码率',
      'keep_temp': '保留临时文件',
      'keep_temp_hint': '便于诊断与手动封装',
      'analysis_results': '识别到的媒体',
      'status': '状态',
      'history': '历史记录',
      'warnings': '提示',
      'appearance': '外观',
      'mode': '模式',
      'system': '跟随系统',
      'light': '浅色',
      'dark': '深色',
      'theme': '主题',
      'language': '语言',
      'battery': '电池优化',
      'battery_hint': '关闭限制可减少后台长任务被系统中断的概率',
      'disable_now': '立即关闭',
      'no_candidates': '当前还没有识别到可下载媒体候选。',
      'select_candidate': '下载前请先选择一个媒体候选。',
      'source_page': '来源页面',
      'extractor': '提取器',
      'completed': '已完成',
      'output_path': '保存文件',
      'analyzing': '正在分析资源…',
      'ready': '候选已就绪',
      'inspector': '资源分析',
      'stream': '流',
      'authorization': '授权请求配置',
      'authorization_hint': '用于自有或已授权站点的 Cookie、User-Agent、Referer 与自定义 Header',
      'cookie_hint': 'name=value; another=value',
      'headers_hint':
          'Authorization: Bearer ...\nX-Requested-With: XMLHttpRequest',
      'core': '核心',
      'score': '评分',
      'segments': '分片',
      'auth_browser_open': '打开授权浏览器',
      'auth_browser_title': '授权会话浏览器',
      'auth_browser_hint': '在这里打开目标站点，由你自己完成登录或真人验证，然后把当前会话导回 FerrisLoad。',
      'auth_browser_hint_inline':
          '当站点要求登录、绑定 Cookie 的播放权限，或出现真人验证页面时，请使用授权浏览器。',
      'auth_browser_address': '浏览器地址',
      'auth_browser_go': '打开',
      'auth_browser_import': '导入当前会话',
      'auth_browser_no_session': '当前页面没有可复用的 Cookie 或浏览器会话。',
      'auth_session_imported': '授权会话已导入，现在可以使用更新后的请求上下文重新分析或下载。',
      'auth_challenge_detected': '检测到访问挑战',
      'auth_challenge_help':
          'FerrisLoad 可以复用你自己完成验证后的会话，但不会绕过 Cloudflare、验证码、封禁、DRM、签名校验或试看限制。',
      'auth_auto_open': '检测到挑战时自动打开授权浏览器',
      'auth_auto_open_hint':
          '当分析或下载遇到登录、限流、Cloudflare 或真人验证挑战时，FerrisLoad 会自动跳转到授权浏览器。',
      'auth_redirecting': '检测到授权挑战，正在打开授权浏览器…',
      'clear_auth_context': '清空已导入会话',
      'preparing': '正在准备下载…',
      'output_not_created': '下载已结束，但没有生成输出文件。请检查资源地址、请求上下文，或重试。',
      'export_failed': '无法将文件导出到所选位置。临时输出：',
      'download_hint': '无需分析即可直接下载：粘贴 m3u8 或直链地址后直接开始。',
    },
    'zh_Hant': {
      'app_title': 'FerrisLoad',
      'app_subtitle': '分析網頁、定位可播放媒體，並下載目前頁面暴露出的最佳核心流。',
      'input_source': '資源位址',
      'source_hint': '貼上網頁、m3u8、mp4、YouTube 或 Bilibili 連結',
      'file_name': '輸出檔案',
      'save_location': '儲存位置',
      'default_location': '預設輸出位置',
      'choose_directory': '選擇目錄',
      'reset_default': '還原預設',
      'analyze': '分析資源',
      'download': '下載已選核心流',
      'download_options': '下載參數',
      'concurrency': '並發',
      'retries': '重試',
      'video_bitrate': '視訊碼率',
      'audio_bitrate': '音訊碼率',
      'keep_temp': '保留暫存檔',
      'keep_temp_hint': '方便診斷與手動封裝',
      'analysis_results': '識別到的媒體',
      'status': '狀態',
      'history': '歷史紀錄',
      'warnings': '提示',
      'appearance': '外觀',
      'mode': '模式',
      'system': '跟隨系統',
      'light': '淺色',
      'dark': '深色',
      'theme': '主題',
      'language': '語言',
      'battery': '電池最佳化',
      'battery_hint': '關閉限制可減少背景長任務被系統中斷的機率',
      'disable_now': '立即關閉',
      'no_candidates': '目前尚未偵測到可下載媒體候選。',
      'select_candidate': '下載前請先選擇一個媒體候選。',
      'source_page': '來源頁面',
      'extractor': '擷取器',
      'completed': '已完成',
      'output_path': '儲存檔案',
      'analyzing': '正在分析資源…',
      'ready': '候選已就緒',
      'inspector': '資源分析',
      'stream': '串流',
      'authorization': '授權請求配置',
      'authorization_hint': '用於自有或已授權站點的 Cookie、User-Agent、Referer 與自訂 Header',
      'cookie_hint': 'name=value; another=value',
      'headers_hint':
          'Authorization: Bearer ...\nX-Requested-With: XMLHttpRequest',
      'core': '核心',
      'score': '評分',
      'segments': '分片',
      'auth_browser_open': '開啟授權瀏覽器',
      'auth_browser_title': '授權會話瀏覽器',
      'auth_browser_hint': '在這裡打開目標站點，由你自行完成登入或真人驗證，然後把目前會話導回 FerrisLoad。',
      'auth_browser_hint_inline':
          '當站點要求登入、綁定 Cookie 的播放權限，或出現真人驗證頁面時，請使用授權瀏覽器。',
      'auth_browser_address': '瀏覽器位址',
      'auth_browser_go': '開啟',
      'auth_browser_import': '匯入目前會話',
      'auth_browser_no_session': '目前頁面沒有可重用的 Cookie 或瀏覽器會話。',
      'auth_session_imported': '授權會話已匯入，現在可以使用更新後的請求上下文重新分析或下載。',
      'auth_challenge_detected': '偵測到存取挑戰',
      'auth_challenge_help':
          'FerrisLoad 可以重用你自行完成驗證後的會話，但不會繞過 Cloudflare、驗證碼、封禁、DRM、簽名校驗或試看限制。',
      'auth_auto_open': '偵測到挑戰時自動開啟授權瀏覽器',
      'auth_auto_open_hint':
          '當分析或下載遇到登入、限流、Cloudflare 或真人驗證挑戰時，FerrisLoad 會自動跳轉到授權瀏覽器。',
      'auth_redirecting': '偵測到授權挑戰，正在開啟授權瀏覽器…',
      'clear_auth_context': '清空已匯入會話',
    },
    'ja': {
      'app_title': 'FerrisLoad',
      'app_subtitle': 'ページを解析し、再生可能なメディアを見つけて、公開された最適なストリームを取得します。',
      'input_source': 'ソース URL',
      'source_hint': 'Web ページ、m3u8、mp4、YouTube、Bilibili のリンクを貼り付け',
      'file_name': '出力ファイル',
      'save_location': '保存先',
      'default_location': '既定の保存先',
      'choose_directory': 'フォルダーを選択',
      'reset_default': '既定に戻す',
      'analyze': '解析',
      'download': '選択したストリームを保存',
      'download_options': 'ダウンロード設定',
      'concurrency': '並列数',
      'retries': '再試行',
      'video_bitrate': '映像ビットレート',
      'audio_bitrate': '音声ビットレート',
      'keep_temp': '一時ファイルを保持',
      'keep_temp_hint': '診断や手動マージに便利',
      'analysis_results': '検出されたメディア',
      'status': '状態',
      'history': '履歴',
      'warnings': '警告',
      'appearance': '外観',
      'mode': 'モード',
      'system': 'システム',
      'light': 'ライト',
      'dark': 'ダーク',
      'theme': 'テーマ',
      'language': '言語',
      'battery': 'バッテリー最適化',
      'battery_hint': '制限を解除すると長時間のバックグラウンド処理が止まりにくくなります',
      'disable_now': '今すぐ無効化',
      'no_candidates': 'まだダウンロード可能な候補は見つかっていません。',
      'select_candidate': 'ダウンロードする前に候補を選択してください。',
      'source_page': 'ソースページ',
      'extractor': '抽出器',
      'completed': '完了',
      'output_path': '保存済みファイル',
      'analyzing': '解析中…',
      'ready': '候補を選択可能',
      'inspector': 'インスペクター',
      'stream': 'ストリーム',
    },
    'ar': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'حلّل الصفحة وحدد الوسائط القابلة للتشغيل ونزّل أفضل تدفق ظاهر في الصفحة.',
      'input_source': 'رابط المصدر',
      'source_hint': 'ألصق رابط صفحة أو m3u8 أو mp4 أو YouTube أو Bilibili',
      'file_name': 'ملف الإخراج',
      'save_location': 'مكان الحفظ',
      'default_location': 'الموقع الافتراضي',
      'choose_directory': 'اختر المجلد',
      'reset_default': 'استخدم الافتراضي',
      'analyze': 'تحليل',
      'download': 'تنزيل التدفق المحدد',
      'download_options': 'خيارات التنزيل',
      'concurrency': 'التوازي',
      'retries': 'إعادات المحاولة',
      'video_bitrate': 'معدل فيديو',
      'audio_bitrate': 'معدل صوت',
      'keep_temp': 'الاحتفاظ بالملفات المؤقتة',
      'keep_temp_hint': 'مفيد للتشخيص والدمج اليدوي',
      'analysis_results': 'الوسائط المكتشفة',
      'status': 'الحالة',
      'history': 'السجل',
      'warnings': 'تنبيهات',
      'appearance': 'المظهر',
      'mode': 'الوضع',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'theme': 'السمة',
      'language': 'اللغة',
      'battery': 'تحسين البطارية',
      'battery_hint':
          'تعطيل القيود يساعد على استمرار التنزيلات الطويلة في الخلفية',
      'disable_now': 'عطّل الآن',
      'no_candidates': 'لم يتم العثور على وسائط قابلة للتنزيل بعد.',
      'select_candidate': 'اختر مرشح وسائط قبل التنزيل.',
      'source_page': 'صفحة المصدر',
      'extractor': 'المستخرج',
      'completed': 'اكتمل',
      'output_path': 'الملف المحفوظ',
      'analyzing': 'جارٍ التحليل...',
      'ready': 'المرشح جاهز',
      'inspector': 'المحلل',
      'stream': 'تدفق',
    },
    'es': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Analiza páginas, encuentra medios reproducibles y descarga el mejor flujo expuesto.',
      'input_source': 'URL de origen',
      'source_hint': 'Pega una página web, m3u8, mp4, YouTube o Bilibili',
      'file_name': 'Archivo de salida',
      'save_location': 'Ubicación de guardado',
      'default_location': 'Ubicación predeterminada',
      'choose_directory': 'Elegir carpeta',
      'reset_default': 'Usar predeterminado',
      'analyze': 'Analizar',
      'download': 'Descargar flujo seleccionado',
      'download_options': 'Opciones de descarga',
      'concurrency': 'Concurrencia',
      'retries': 'Reintentos',
      'video_bitrate': 'Bitrate de video',
      'audio_bitrate': 'Bitrate de audio',
      'keep_temp': 'Conservar temporales',
      'keep_temp_hint': 'Útil para diagnóstico y remux manual',
      'analysis_results': 'Medios detectados',
      'status': 'Estado',
      'history': 'Historial',
      'warnings': 'Advertencias',
      'appearance': 'Apariencia',
      'mode': 'Modo',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'theme': 'Tema',
      'language': 'Idioma',
      'battery': 'Optimización de batería',
      'battery_hint':
          'Desactivar restricciones ayuda a mantener descargas largas en segundo plano',
      'disable_now': 'Desactivar ahora',
      'no_candidates': 'Aún no se detectaron medios descargables.',
      'select_candidate': 'Selecciona un candidato antes de descargar.',
      'source_page': 'Página fuente',
      'extractor': 'Extractor',
      'completed': 'Completado',
      'output_path': 'Archivo guardado',
      'analyzing': 'Analizando...',
      'ready': 'Candidato listo',
      'inspector': 'Inspector',
      'stream': 'Flujo',
    },
    'ru': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Анализируйте страницу, находите воспроизводимое медиа и сохраняйте лучший открытый поток.',
      'input_source': 'URL источника',
      'source_hint':
          'Вставьте ссылку на страницу, m3u8, mp4, YouTube или Bilibili',
      'file_name': 'Выходной файл',
      'save_location': 'Папка сохранения',
      'default_location': 'Папка по умолчанию',
      'choose_directory': 'Выбрать папку',
      'reset_default': 'По умолчанию',
      'analyze': 'Анализировать',
      'download': 'Скачать выбранный поток',
      'download_options': 'Параметры загрузки',
      'concurrency': 'Параллельность',
      'retries': 'Повторы',
      'video_bitrate': 'Битрейт видео',
      'audio_bitrate': 'Битрейт аудио',
      'keep_temp': 'Сохранять временные файлы',
      'keep_temp_hint': 'Полезно для диагностики и ручной сборки',
      'analysis_results': 'Обнаруженные медиа',
      'status': 'Состояние',
      'history': 'История',
      'warnings': 'Предупреждения',
      'appearance': 'Оформление',
      'mode': 'Режим',
      'system': 'Система',
      'light': 'Светлый',
      'dark': 'Тёмный',
      'theme': 'Тема',
      'language': 'Язык',
      'battery': 'Оптимизация батареи',
      'battery_hint':
          'Отключение ограничений снижает риск остановки фоновых загрузок',
      'disable_now': 'Отключить',
      'no_candidates': 'Подходящие медиа ещё не найдены.',
      'select_candidate': 'Перед загрузкой выберите один из потоков.',
      'source_page': 'Страница',
      'extractor': 'Извлекатель',
      'completed': 'Готово',
      'output_path': 'Сохранённый файл',
      'analyzing': 'Анализ...',
      'ready': 'Кандидат готов',
      'inspector': 'Инспектор',
      'stream': 'Поток',
    },
    'hi': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'पेज का विश्लेषण करें, चलने योग्य मीडिया खोजें और सर्वश्रेष्ठ उपलब्ध स्ट्रीम डाउनलोड करें।',
      'input_source': 'स्रोत URL',
      'source_hint': 'वेबपेज, m3u8, mp4, YouTube या Bilibili लिंक चिपकाएँ',
      'file_name': 'आउटपुट फ़ाइल',
      'save_location': 'सेव स्थान',
      'default_location': 'डिफ़ॉल्ट स्थान',
      'choose_directory': 'फ़ोल्डर चुनें',
      'reset_default': 'डिफ़ॉल्ट उपयोग करें',
      'analyze': 'विश्लेषण करें',
      'download': 'चयनित स्ट्रीम डाउनलोड करें',
      'download_options': 'डाउनलोड विकल्प',
      'concurrency': 'समांतरता',
      'retries': 'पुनः प्रयास',
      'video_bitrate': 'वीडियो बिटरेट',
      'audio_bitrate': 'ऑडियो बिटरेट',
      'keep_temp': 'अस्थायी फ़ाइलें रखें',
      'keep_temp_hint': 'डायग्नोस्टिक और मैन्युअल रीमिक्स के लिए उपयोगी',
      'analysis_results': 'मिले हुए मीडिया',
      'status': 'स्थिति',
      'history': 'इतिहास',
      'warnings': 'चेतावनी',
      'appearance': 'रूप',
      'mode': 'मोड',
      'system': 'सिस्टम',
      'light': 'लाइट',
      'dark': 'डार्क',
      'theme': 'थीम',
      'language': 'भाषा',
      'battery': 'बैटरी अनुकूलन',
      'battery_hint':
          'प्रतिबंध बंद करने से लंबे बैकग्राउंड डाउनलोड रुकने की संभावना कम होती है',
      'disable_now': 'अभी बंद करें',
      'no_candidates': 'अभी तक कोई डाउनलोड योग्य मीडिया नहीं मिला।',
      'select_candidate': 'डाउनलोड से पहले कोई मीडिया चुनें।',
      'source_page': 'स्रोत पेज',
      'extractor': 'एक्सट्रैक्टर',
      'completed': 'पूर्ण',
      'output_path': 'सहेजी गई फ़ाइल',
      'analyzing': 'विश्लेषण हो रहा है...',
      'ready': 'उम्मीदवार तैयार है',
      'inspector': 'इंस्पेक्टर',
      'stream': 'स्ट्रीम',
    },
    'fr': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Analysez une page, repérez les médias lisibles et téléchargez le meilleur flux exposé.',
      'input_source': 'URL source',
      'source_hint': 'Collez un lien page web, m3u8, mp4, YouTube ou Bilibili',
      'file_name': 'Fichier de sortie',
      'save_location': 'Emplacement',
      'default_location': 'Emplacement par défaut',
      'choose_directory': 'Choisir un dossier',
      'reset_default': 'Par défaut',
      'analyze': 'Analyser',
      'download': 'Télécharger le flux choisi',
      'download_options': 'Options de téléchargement',
      'concurrency': 'Concurrence',
      'retries': 'Réessais',
      'video_bitrate': 'Débit vidéo',
      'audio_bitrate': 'Débit audio',
      'keep_temp': 'Conserver les fichiers temporaires',
      'keep_temp_hint': 'Utile pour le diagnostic et le remux manuel',
      'analysis_results': 'Médias détectés',
      'status': 'Statut',
      'history': 'Historique',
      'warnings': 'Avertissements',
      'appearance': 'Apparence',
      'mode': 'Mode',
      'system': 'Système',
      'light': 'Clair',
      'dark': 'Sombre',
      'theme': 'Thème',
      'language': 'Langue',
      'battery': 'Optimisation batterie',
      'battery_hint':
          'Désactiver les restrictions limite l’arrêt des longues tâches en arrière-plan',
      'disable_now': 'Désactiver',
      'no_candidates': 'Aucun média téléchargeable détecté pour le moment.',
      'select_candidate': 'Sélectionnez un média avant de télécharger.',
      'source_page': 'Page source',
      'extractor': 'Extracteur',
      'completed': 'Terminé',
      'output_path': 'Fichier enregistré',
      'analyzing': 'Analyse en cours...',
      'ready': 'Candidat prêt',
      'inspector': 'Inspecteur',
      'stream': 'Flux',
    },
    'de': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Analysiere Seiten, finde abspielbare Medien und lade den besten offengelegten Stream herunter.',
      'input_source': 'Quell-URL',
      'source_hint':
          'Webseite, m3u8, mp4, YouTube- oder Bilibili-Link einfügen',
      'file_name': 'Ausgabedatei',
      'save_location': 'Speicherort',
      'default_location': 'Standardordner',
      'choose_directory': 'Ordner wählen',
      'reset_default': 'Standard verwenden',
      'analyze': 'Analysieren',
      'download': 'Ausgewählten Stream laden',
      'download_options': 'Downloadoptionen',
      'concurrency': 'Parallelität',
      'retries': 'Wiederholungen',
      'video_bitrate': 'Video-Bitrate',
      'audio_bitrate': 'Audio-Bitrate',
      'keep_temp': 'Temporäre Dateien behalten',
      'keep_temp_hint': 'Hilfreich für Diagnose und manuelles Remuxen',
      'analysis_results': 'Erkannte Medien',
      'status': 'Status',
      'history': 'Verlauf',
      'warnings': 'Hinweise',
      'appearance': 'Darstellung',
      'mode': 'Modus',
      'system': 'System',
      'light': 'Hell',
      'dark': 'Dunkel',
      'theme': 'Thema',
      'language': 'Sprache',
      'battery': 'Akku-Optimierung',
      'battery_hint':
          'Weniger Einschränkungen verhindern Abbrüche langer Hintergrunddownloads',
      'disable_now': 'Jetzt deaktivieren',
      'no_candidates': 'Noch keine herunterladbaren Medien erkannt.',
      'select_candidate': 'Vor dem Download bitte einen Stream auswählen.',
      'source_page': 'Quellseite',
      'extractor': 'Extraktor',
      'completed': 'Abgeschlossen',
      'output_path': 'Gespeicherte Datei',
      'analyzing': 'Analyse läuft...',
      'ready': 'Kandidat bereit',
      'inspector': 'Inspektor',
      'stream': 'Stream',
    },
    'pt': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Analise páginas, localize mídia reproduzível e baixe o melhor fluxo exposto.',
      'input_source': 'URL de origem',
      'source_hint': 'Cole uma página, m3u8, mp4, YouTube ou Bilibili',
      'file_name': 'Arquivo de saída',
      'save_location': 'Local de salvamento',
      'default_location': 'Local padrão',
      'choose_directory': 'Escolher pasta',
      'reset_default': 'Usar padrão',
      'analyze': 'Analisar',
      'download': 'Baixar fluxo selecionado',
      'download_options': 'Opções de download',
      'concurrency': 'Concorrência',
      'retries': 'Tentativas',
      'video_bitrate': 'Bitrate de vídeo',
      'audio_bitrate': 'Bitrate de áudio',
      'keep_temp': 'Manter temporários',
      'keep_temp_hint': 'Útil para diagnóstico e remux manual',
      'analysis_results': 'Mídias detectadas',
      'status': 'Status',
      'history': 'Histórico',
      'warnings': 'Avisos',
      'appearance': 'Aparência',
      'mode': 'Modo',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Escuro',
      'theme': 'Tema',
      'language': 'Idioma',
      'battery': 'Otimização de bateria',
      'battery_hint':
          'Desativar restrições ajuda downloads longos em segundo plano',
      'disable_now': 'Desativar agora',
      'no_candidates': 'Nenhuma mídia baixável foi detectada ainda.',
      'select_candidate': 'Selecione uma mídia antes de baixar.',
      'source_page': 'Página de origem',
      'extractor': 'Extrator',
      'completed': 'Concluído',
      'output_path': 'Arquivo salvo',
      'analyzing': 'Analisando...',
      'ready': 'Candidato pronto',
      'inspector': 'Inspetor',
      'stream': 'Fluxo',
    },
    'tr': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Sayfayı analiz edin, oynatılabilir medyayı bulun ve açıkta olan en iyi akışı indirin.',
      'input_source': 'Kaynak URL',
      'source_hint':
          'Web sayfası, m3u8, mp4, YouTube veya Bilibili bağlantısı yapıştırın',
      'file_name': 'Çıktı dosyası',
      'save_location': 'Kayıt konumu',
      'default_location': 'Varsayılan konum',
      'choose_directory': 'Klasör seç',
      'reset_default': 'Varsayılanı kullan',
      'analyze': 'Analiz et',
      'download': 'Seçili akışı indir',
      'download_options': 'İndirme seçenekleri',
      'concurrency': 'Eşzamanlılık',
      'retries': 'Yeniden deneme',
      'video_bitrate': 'Video bit hızı',
      'audio_bitrate': 'Ses bit hızı',
      'keep_temp': 'Geçici dosyaları sakla',
      'keep_temp_hint': 'Tanılama ve elle birleştirme için yararlı',
      'analysis_results': 'Bulunan medya',
      'status': 'Durum',
      'history': 'Geçmiş',
      'warnings': 'Uyarılar',
      'appearance': 'Görünüm',
      'mode': 'Mod',
      'system': 'Sistem',
      'light': 'Açık',
      'dark': 'Koyu',
      'theme': 'Tema',
      'language': 'Dil',
      'battery': 'Pil optimizasyonu',
      'battery_hint':
          'Kısıtlamaları kapatmak uzun arka plan indirmelerini korur',
      'disable_now': 'Şimdi kapat',
      'no_candidates': 'Henüz indirilebilir medya bulunamadı.',
      'select_candidate': 'İndirmeden önce bir medya adayı seçin.',
      'source_page': 'Kaynak sayfa',
      'extractor': 'Çıkarıcı',
      'completed': 'Tamamlandı',
      'output_path': 'Kaydedilen dosya',
      'analyzing': 'Analiz ediliyor...',
      'ready': 'Aday hazır',
      'inspector': 'İnceleyici',
      'stream': 'Akış',
    },
    'vi': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Phân tích trang, tìm media có thể phát và tải luồng tốt nhất đang được lộ ra.',
      'input_source': 'URL nguồn',
      'source_hint': 'Dán liên kết web, m3u8, mp4, YouTube hoặc Bilibili',
      'file_name': 'Tệp đầu ra',
      'save_location': 'Nơi lưu',
      'default_location': 'Vị trí mặc định',
      'choose_directory': 'Chọn thư mục',
      'reset_default': 'Dùng mặc định',
      'analyze': 'Phân tích',
      'download': 'Tải luồng đã chọn',
      'download_options': 'Tùy chọn tải',
      'concurrency': 'Đồng thời',
      'retries': 'Thử lại',
      'video_bitrate': 'Bitrate video',
      'audio_bitrate': 'Bitrate âm thanh',
      'keep_temp': 'Giữ tệp tạm',
      'keep_temp_hint': 'Hữu ích cho chẩn đoán và ghép tay',
      'analysis_results': 'Media đã phát hiện',
      'status': 'Trạng thái',
      'history': 'Lịch sử',
      'warnings': 'Cảnh báo',
      'appearance': 'Giao diện',
      'mode': 'Chế độ',
      'system': 'Hệ thống',
      'light': 'Sáng',
      'dark': 'Tối',
      'theme': 'Chủ đề',
      'language': 'Ngôn ngữ',
      'battery': 'Tối ưu pin',
      'battery_hint': 'Tắt hạn chế giúp tải nền dài không bị dừng',
      'disable_now': 'Tắt ngay',
      'no_candidates': 'Chưa phát hiện media có thể tải.',
      'select_candidate': 'Hãy chọn một mục trước khi tải.',
      'source_page': 'Trang nguồn',
      'extractor': 'Bộ tách',
      'completed': 'Hoàn tất',
      'output_path': 'Tệp đã lưu',
      'analyzing': 'Đang phân tích...',
      'ready': 'Ứng viên sẵn sàng',
      'inspector': 'Trình phân tích',
      'stream': 'Luồng',
    },
    'id': {
      'app_title': 'FerrisLoad',
      'app_subtitle':
          'Analisis halaman, temukan media yang bisa diputar, lalu unduh aliran terbaik yang terlihat.',
      'input_source': 'URL sumber',
      'source_hint': 'Tempel tautan web, m3u8, mp4, YouTube, atau Bilibili',
      'file_name': 'Berkas keluaran',
      'save_location': 'Lokasi simpan',
      'default_location': 'Lokasi bawaan',
      'choose_directory': 'Pilih folder',
      'reset_default': 'Pakai bawaan',
      'analyze': 'Analisis',
      'download': 'Unduh aliran terpilih',
      'download_options': 'Opsi unduhan',
      'concurrency': 'Konkruensi',
      'retries': 'Ulangi',
      'video_bitrate': 'Bitrate video',
      'audio_bitrate': 'Bitrate audio',
      'keep_temp': 'Simpan berkas sementara',
      'keep_temp_hint': 'Berguna untuk diagnostik dan remux manual',
      'analysis_results': 'Media terdeteksi',
      'status': 'Status',
      'history': 'Riwayat',
      'warnings': 'Peringatan',
      'appearance': 'Tampilan',
      'mode': 'Mode',
      'system': 'Sistem',
      'light': 'Terang',
      'dark': 'Gelap',
      'theme': 'Tema',
      'language': 'Bahasa',
      'battery': 'Optimisasi baterai',
      'battery_hint':
          'Mematikan pembatasan membantu unduhan latar belakang yang panjang',
      'disable_now': 'Matikan sekarang',
      'no_candidates': 'Belum ada media yang dapat diunduh terdeteksi.',
      'select_candidate': 'Pilih kandidat media sebelum mengunduh.',
      'source_page': 'Halaman sumber',
      'extractor': 'Ekstraktor',
      'completed': 'Selesai',
      'output_path': 'Berkas tersimpan',
      'analyzing': 'Menganalisis...',
      'ready': 'Kandidat siap',
      'inspector': 'Inspektur',
      'stream': 'Aliran',
    },
  };

  String text(String key) {
    final bundle = _strings[_lookupKey] ?? _strings[_fallbackLocale]!;
    return bundle[key] ?? _strings[_fallbackLocale]![key] ?? key;
  }

  String localeLabel(Locale locale) {
    final key = locale.scriptCode == null
        ? locale.languageCode
        : '${locale.languageCode}_${locale.scriptCode}';
    return localeLabels[key] ?? localeLabels[locale.languageCode] ?? key;
  }

  String get _lookupKey {
    if (locale.scriptCode != null) {
      final composite = '${locale.languageCode}_${locale.scriptCode}';
      if (_strings.containsKey(composite)) {
        return composite;
      }
    }
    if (_strings.containsKey(locale.languageCode)) {
      return locale.languageCode;
    }
    return _fallbackLocale;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (item) =>
          item.languageCode == locale.languageCode &&
          (item.scriptCode == null || item.scriptCode == locale.scriptCode),
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}
